force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/IATA_code__c.field-meta.xml
<CustomField>
    <fullName>IATA_code__c</fullName>
    <label>IATA code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACA-Mexico</fullName>
                <default>true</default>
                <label>ACA-Mexico</label>
            </value>
            <value>
                <fullName>AEP-Argentina</fullName>
            </value>
            <value>
                <fullName>AQP-Peru</fullName>
            </value>
            <value>
                <fullName>ARR-Argentina</fullName>
            </value>
            <value>
                <fullName>ASU-Paraguay</fullName>
            </value>
            <value>
                <fullName>AVI-Cuba</fullName>
            </value>
            <value>
                <fullName>BBA-Chile</fullName>
            </value>
            <value>
                <fullName>BCL-Costa Rica</fullName>
            </value>
            <value>
                <fullName>BEL-Brazil</fullName>
            </value>
            <value>
                <fullName>BFH-Brazil</fullName>
            </value>
            <value>
                <fullName>BJO-Bolivia</fullName>
            </value>
            <value>
                <fullName>BLA-Venezuela</fullName>
            </value>
            <value>
                <fullName>BPS-Brazil</fullName>
            </value>
            <value>
                <fullName>BRC-Argentina</fullName>
            </value>
            <value>
                <fullName>BSB-Brazil</fullName>
            </value>
            <value>
                <fullName>CCP-Chile</fullName>
            </value>
            <value>
                <fullName>CCS-Venezuela</fullName>
            </value>
            <value>
                <fullName>CFB-Brazil</fullName>
            </value>
            <value>
                <fullName>CGH-Brazil</fullName>
            </value>
            <value>
                <fullName>CGR-Brazil</fullName>
            </value>
            <value>
                <fullName>CJC-Chile</fullName>
            </value>
            <value>
                <fullName>CNF-Brazil</fullName>
            </value>
            <value>
                <fullName>COR-Argentina</fullName>
            </value>
            <value>
                <fullName>CPC-Argentina</fullName>
            </value>
            <value>
                <fullName>CUN-Mexico</fullName>
            </value>
            <value>
                <fullName>CWB-Brazil</fullName>
            </value>
            <value>
                <fullName>CYO-Cuba</fullName>
            </value>
            <value>
                <fullName>CZM-Mexico</fullName>
            </value>
            <value>
                <fullName>DZO-Uruguay</fullName>
            </value>
            <value>
                <fullName>EPA-Argentina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Arrival_airport__c.field-meta.xml
<CustomField>
    <fullName>Arrival_airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival)</relationshipLabel>
    <relationshipName>Flights1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure_airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Flight_distance__c.field-meta.xml
<CustomField>
    <fullName>Flight_distance__c</fullName>
    <label>Flight distance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FlightController.cls
public class FlightController {
    @AuraEnabled
    public static List<Airport__c> getAirportsByIATA(String iataCode) {
        // Consulta la base de datos para obtener aeropuertos con el código IATA proporcionado
        List<Airport__c> airports = [SELECT Id, Name, IATA_Code__c, Latitude__c, Longitude__c FROM Airport__c WHERE IATA_Code__c = :iataCode LIMIT 1];
        
        return airports;
    }

    @AuraEnabled
    public static void createFlight(String departureAirportId, String arrivalAirportId, Decimal flightDistance) {
        Flight__c newFlight = new Flight__c();
        newFlight.Departure_Airport__c = departureAirportId;
        newFlight.Arrival_Airport__c = arrivalAirportId;
        newFlight.Flight_Distance__c = flightDistance;

        try {
            insert newFlight;
        } catch (Exception e) {
            System.debug('Error al insertar el vuelo: ' + e.getMessage());
            throw new AuraHandledException('Error al guardar el vuelo');
        }
    }
}